# Generated by Django 4.2.3 on 2023-08-02 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_alter_meal_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='on_special_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9999),
        ),
    ]
