# Generated by Django 4.2.3 on 2023-08-02 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_alter_meal_on_special_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='on_special',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
