# Generated by Django 4.2.3 on 2023-08-02 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0005_alter_meal_on_special'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='on_special',
            field=models.BooleanField(default=False),
        ),
    ]
