# Generated by Django 4.2.3 on 2023-08-02 13:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0007_alter_meal_on_special_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='on_special_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9999, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='meal',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9999, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
