# Generated by Django 4.2.3 on 2023-07-26 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageOne', models.ImageField(upload_to='home/gallery')),
                ('imageTwo', models.ImageField(upload_to='home/gallery')),
                ('imageThree', models.ImageField(upload_to='home/gallery')),
                ('imageFour', models.ImageField(upload_to='home/gallery')),
            ],
        ),
        migrations.CreateModel(
            name='OurStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('imageOne', models.ImageField(upload_to='home/our-story')),
                ('imageTwo', models.ImageField(upload_to='home/our-story')),
                ('imageThree', models.ImageField(upload_to='home/our-story')),
                ('imageFour', models.ImageField(upload_to='home/our-story')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('serviceImage', models.ImageField(upload_to='home/service')),
            ],
        ),
        migrations.CreateModel(
            name='Sliders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider', models.ImageField(null=True, upload_to='home/sliders')),
            ],
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
