# Generated by Django 4.2.3 on 2023-07-28 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_gallery_options_alter_ourstory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourstory',
            name='chef_image',
            field=models.ImageField(blank=True, null=True, upload_to='home/Chef'),
        ),
    ]
