# Generated by Django 4.2.3 on 2023-07-28 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_ourstory_chef_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourstory',
            name='chefName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ourstory',
            name='chefTitle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
