# Generated by Django 4.2.3 on 2023-07-29 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_ourstory_chefname_ourstory_cheftitle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='imageFour',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='imageOne',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='imageThree',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='imageTwo',
        ),
    ]
